export const EMOJI_OPTIONS: {
  hexcode: string;
  label: string;
  group: string;
}[] = [
  // ── Keuangan ──────────────────────────────────────────────────────────────
  { hexcode: "1F4B0", label: "Uang Koin", group: "Keuangan" },
  { hexcode: "1F4B5", label: "Uang Kertas", group: "Keuangan" },
  { hexcode: "1F4B3", label: "Kartu Kredit", group: "Keuangan" },
  { hexcode: "1F4B8", label: "Uang Terbang", group: "Keuangan" },
  { hexcode: "1F4B9", label: "Grafik Naik", group: "Keuangan" },
  { hexcode: "1F3E6", label: "Bank", group: "Keuangan" },
  { hexcode: "1F4B1", label: "Tukar Mata Uang", group: "Keuangan" },
  { hexcode: "1FA99", label: "Koin", group: "Keuangan" },
  { hexcode: "1F4B2", label: "Dolar", group: "Keuangan" },
  { hexcode: "1F4B4", label: "Yen", group: "Keuangan" },
  { hexcode: "1F4B6", label: "Euro", group: "Keuangan" },
  { hexcode: "1F4B7", label: "Poundsterling", group: "Keuangan" },
  { hexcode: "1F4CA", label: "Statistik", group: "Keuangan" },
  { hexcode: "1F4C9", label: "Grafik Turun", group: "Keuangan" },
  { hexcode: "1F516", label: "Bookmark", group: "Keuangan" },

  // ── Makanan & Minuman ─────────────────────────────────────────────────────
  { hexcode: "1F35C", label: "Ramen", group: "Makanan" },
  { hexcode: "1F372", label: "Soto", group: "Makanan" },
  { hexcode: "1F35B", label: "Kari", group: "Makanan" },
  { hexcode: "1F354", label: "Burger", group: "Makanan" },
  { hexcode: "1F355", label: "Pizza", group: "Makanan" },
  { hexcode: "1F35F", label: "Kentang Goreng", group: "Makanan" },
  { hexcode: "1F371", label: "Bento", group: "Makanan" },
  { hexcode: "1F96A", label: "Sandwich", group: "Makanan" },
  { hexcode: "1F366", label: "Es Krim", group: "Makanan" },
  { hexcode: "1F370", label: "Kue", group: "Makanan" },
  { hexcode: "2615", label: "Kopi", group: "Makanan" },
  { hexcode: "1F9CB", label: "Bubble Tea", group: "Makanan" },
  { hexcode: "1F37A", label: "Bir", group: "Makanan" },
  { hexcode: "1F964", label: "Minuman", group: "Makanan" },
  { hexcode: "1F9FA", label: "Belanja Makanan", group: "Makanan" },
  { hexcode: "1F34E", label: "Buah", group: "Makanan" },

  // ── Transportasi ─────────────────────────────────────────────────────────
  { hexcode: "1F697", label: "Mobil", group: "Transportasi" },
  { hexcode: "1F68C", label: "Bus", group: "Transportasi" },
  { hexcode: "1F682", label: "Kereta", group: "Transportasi" },
  { hexcode: "1F6B2", label: "Sepeda", group: "Transportasi" },
  { hexcode: "1F6F5", label: "Motor", group: "Transportasi" },
  { hexcode: "2708", label: "Pesawat", group: "Transportasi" },
  { hexcode: "1F6A2", label: "Kapal", group: "Transportasi" },
  { hexcode: "26FD", label: "BBM / SPBU", group: "Transportasi" },
  { hexcode: "1F17F", label: "Parkir", group: "Transportasi" },
  { hexcode: "1F695", label: "Taksi", group: "Transportasi" },
  { hexcode: "1F6EB", label: "Naik Pesawat", group: "Transportasi" },
  { hexcode: "1F9F3", label: "Koper", group: "Transportasi" },

  // ── Belanja ───────────────────────────────────────────────────────────────
  { hexcode: "1F6CD", label: "Tas Belanja", group: "Belanja" },
  { hexcode: "1F6D2", label: "Troli Belanja", group: "Belanja" },
  { hexcode: "1F381", label: "Hadiah", group: "Belanja" },
  { hexcode: "1F4E6", label: "Paket", group: "Belanja" },
  { hexcode: "1F455", label: "Kemeja", group: "Belanja" },
  { hexcode: "1F457", label: "Gaun", group: "Belanja" },
  { hexcode: "1F45F", label: "Sepatu", group: "Belanja" },
  { hexcode: "1F453", label: "Kacamata", group: "Belanja" },
  { hexcode: "1F484", label: "Lipstik / Kosmetik", group: "Belanja" },
  { hexcode: "1F48D", label: "Cincin / Perhiasan", group: "Belanja" },
  { hexcode: "1F4F1", label: "HP", group: "Belanja" },
  { hexcode: "1F5A5", label: "Komputer / Gadget", group: "Belanja" },

  // ── Rumah & Tagihan ───────────────────────────────────────────────────────
  { hexcode: "1F3E0", label: "Rumah", group: "Rumah" },
  { hexcode: "1F6CB", label: "Furnitur", group: "Rumah" },
  { hexcode: "1F4A1", label: "Listrik", group: "Rumah" },
  { hexcode: "1F6B0", label: "Air", group: "Rumah" },
  { hexcode: "1F525", label: "Gas", group: "Rumah" },
  { hexcode: "1F528", label: "Perbaikan", group: "Rumah" },
  { hexcode: "1F4FA", label: "TV / Internet", group: "Rumah" },
  { hexcode: "1F9F9", label: "Kebersihan", group: "Rumah" },
  { hexcode: "1F511", label: "Sewa Kontrakan", group: "Rumah" },
  { hexcode: "1F6AA", label: "Pintu", group: "Rumah" },
  { hexcode: "1F9F4", label: "Peralatan Dapur", group: "Rumah" },
  { hexcode: "1F6D1", label: "Asuransi", group: "Rumah" },

  // ── Kesehatan ─────────────────────────────────────────────────────────────
  { hexcode: "1F3E5", label: "Rumah Sakit", group: "Kesehatan" },
  { hexcode: "1F48A", label: "Obat", group: "Kesehatan" },
  { hexcode: "1FA7A", label: "Periksa Dokter", group: "Kesehatan" },
  { hexcode: "1F9EA", label: "Vitamin / Suplemen", group: "Kesehatan" },
  { hexcode: "1F3CB", label: "Gym", group: "Kesehatan" },
  { hexcode: "1F9D8", label: "Yoga", group: "Kesehatan" },
  { hexcode: "1F6C1", label: "Perawatan Diri", group: "Kesehatan" },
  { hexcode: "1FAE6", label: "Gigi", group: "Kesehatan" },
  { hexcode: "1F9E0", label: "Kesehatan Mental", group: "Kesehatan" },
  { hexcode: "2764", label: "Jantung Sehat", group: "Kesehatan" },

  // ── Hiburan ───────────────────────────────────────────────────────────────
  { hexcode: "1F3B5", label: "Musik", group: "Hiburan" },
  { hexcode: "1F3AE", label: "Game", group: "Hiburan" },
  { hexcode: "1F3AC", label: "Film / Netflix", group: "Hiburan" },
  { hexcode: "1F4DA", label: "Buku", group: "Hiburan" },
  { hexcode: "1F3A8", label: "Seni", group: "Hiburan" },
  { hexcode: "1F4F7", label: "Foto", group: "Hiburan" },
  { hexcode: "1F3A4", label: "Karaoke", group: "Hiburan" },
  { hexcode: "26BD", label: "Olahraga", group: "Hiburan" },
  { hexcode: "1F3D6", label: "Liburan Pantai", group: "Hiburan" },
  { hexcode: "1F3D4", label: "Liburan Gunung", group: "Hiburan" },
  { hexcode: "1F3AA", label: "Event / Tiket", group: "Hiburan" },
  { hexcode: "1F9E9", label: "Hobi", group: "Hiburan" },

  // ── Pendidikan ────────────────────────────────────────────────────────────
  { hexcode: "1F393", label: "Sekolah / Kuliah", group: "Pendidikan" },
  { hexcode: "1F4D6", label: "Kursus / Buku", group: "Pendidikan" },
  { hexcode: "270F", label: "ATK", group: "Pendidikan" },
  { hexcode: "1F4BB", label: "Laptop Belajar", group: "Pendidikan" },
  { hexcode: "1F310", label: "Kursus Online", group: "Pendidikan" },
  { hexcode: "1F9D1-200D-1F4BB", label: "Les Privat", group: "Pendidikan" },
  { hexcode: "1F4C3", label: "SPP", group: "Pendidikan" },

  // ── Pemasukan ─────────────────────────────────────────────────────────────
  { hexcode: "1F4BC", label: "Gaji / Kantor", group: "Pemasukan" },
  { hexcode: "1F3E2", label: "Bisnis", group: "Pemasukan" },
  { hexcode: "2B50", label: "Bonus", group: "Pemasukan" },
  { hexcode: "1F91D", label: "Freelance", group: "Pemasukan" },
  { hexcode: "1F4C8", label: "Dividen / Investasi", group: "Pemasukan" },
  { hexcode: "1FA84", label: "Passive Income", group: "Pemasukan" },
  { hexcode: "1F38A", label: "THR / Hadiah", group: "Pemasukan" },
  { hexcode: "1F4E9", label: "Transfer Masuk", group: "Pemasukan" },

  // ── Lainnya ───────────────────────────────────────────────────────────────
  { hexcode: "1F4AC", label: "Lainnya", group: "Lainnya" },
  { hexcode: "2753", label: "Tak Terduga", group: "Lainnya" },
  { hexcode: "26A1", label: "Darurat", group: "Lainnya" },
  { hexcode: "1F4E4", label: "Transfer Keluar", group: "Lainnya" },
  { hexcode: "1F4DD", label: "Catatan", group: "Lainnya" },
  { hexcode: "1F512", label: "Tabungan Kunci", group: "Lainnya" },
  { hexcode: "267B", label: "Cicilan / Utang", group: "Lainnya" },
  { hexcode: "1F4CB", label: "Laporan", group: "Lainnya" },
];
